### ISSUE TITLE
Return correct file sizes from xFileSize

### ISSUE THREAD

**Issue by simonwo** [uktrade/sqlite-s3vfs#1]
The File size stuff could probably be better – I had an idea that you could make the last block actually be the correct size instead of just requiring all blocks be 64kb, and then you can easily work out the file size by just summing the file sizes of all the blocks from an AWS HEAD call, but I didn't implement that.

This probably won't cause many problems but it would be confusing if SQLite was to xTruncate a file to a certain size and then subsequently read back the size and it be different to expected.

**Comment by michalc** [comment]
After going round the houses far too much, I finally realised that SQLite doesn't leap ahead and write pages without having written previous pages first. So in terms of blocks, _never_ padding any block with zero bytes means that all blocks will end up the same size except the last one.

So now (as of v0.0.10):

- xFileSize is accurate, and is done just by summing sizes of objects in S3
- serialization is similarly unaware of anything page or block size-related, and is done just by concatenating the objects
- and truncation (which is called by VACUUM) works as expected, without any block or page-size knowledge
