### ISSUE TITLE
Pypi page doesn't point at this source repo

### ISSUE THREAD

**Issue by stuaxo** [uktrade/sqlite-s3vfs#9]
It would be good if the pypi page pointed at this source repository, the homepage should be set there too, possibly to a readthedocs repository for sqlite-s3vfs

**Comment by michalc** [comment]
Hello! 👋 

To check, which links should be set and where?

(I'm looking at https://pypi.org/project/sqlite-s3vfs/, and I see the homepage set to https://github.com/uktrade/sqlite-s3vfs, which I think is reasonable in the absence of readthedocs?)

**Comment by stuaxo** [comment]
Ah, that is indeed correct.

I think I just had the Window small / zoomed in and it collapsed the part of the page that was on.
